# Generated by Django 4.2.5 on 2023-10-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('urgency', models.IntegerField(choices=[(1, '1 Week'), (2, '3 Days'), (3, '1 Day')])),
                ('quantity', models.IntegerField()),
                ('task_type', models.IntegerField(choices=[(1, 'Repair'), (2, 'Modification'), (3, 'Fabrication'), (4, 'Other')])),
                ('machining', models.BooleanField(default=False)),
                ('assessment_time', models.DurationField(blank=True)),
                ('is_planned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('FM1', 'FM1'), ('FM2', 'FM2'), ('FMM', 'FMM'), ('HO', 'Head Office'), ('KNT', 'KNT'), ('NP5', 'NP5'), ('SML', 'SML')], max_length=10)),
                ('department', models.CharField(blank=True, choices=[('AUTO', 'Automotive'), ('ELEC', 'Electrical'), ('HR', 'HR'), ('MAINT', 'Maintenance'), ('RND', 'RnD'), ('UTL', 'Utility')], max_length=50)),
                ('date', models.DateField()),
                ('requester', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worker_type', models.CharField(choices=[('Local', 'Local'), ('Expat', 'Expat')], max_length=10)),
                ('pay_rate', models.FloatField()),
                ('expertise', models.ManyToManyField(to='workshop.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_spent', models.DurationField()),
                ('total_manpower_cost', models.FloatField()),
                ('total_material_cost', models.FloatField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workshop.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='work_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workshop.workrequest'),
        ),
        migrations.CreateModel(
            name='StateDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'New'), (2, 'Queued'), (3, 'Awaiting Material'), (4, 'In Progress'), (5, 'Completed'), (6, 'Cancelled')])),
                ('start_time', models.DateField()),
                ('end_time', models.DateField(blank=True, null=True)),
                ('normal_duration', models.DurationField()),
                ('overtime_duration', models.DurationField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.task')),
                ('workers', models.ManyToManyField(to='workshop.worker')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('cost', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='workshop.taskreport')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('received', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.task')),
            ],
        ),
    ]
