# Generated by Django 4.2.4 on 2023-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_workrequest_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assessment_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
