# Generated by Django 4.2.4 on 2023-10-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_task_assessment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assessment_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
