# Generated by Django 4.2.4 on 2023-10-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_task_assessment_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateduration',
            name='state',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Queued'), (3, 'Back Load'), (4, 'Awaiting Material'), (5, 'In Progress'), (6, 'Completed'), (7, 'Cancelled')]),
        ),
    ]
