# Generated by Django 4.2.4 on 2023-10-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_stateduration_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateduration',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stateduration',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
