# Generated by Django 4.2.4 on 2023-10-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_stateduration_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateduration',
            name='normal_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='stateduration',
            name='overtime_duration',
            field=models.DurationField(null=True),
        ),
    ]
