# Generated by Django 4.2.4 on 2023-10-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_alter_stateduration_normal_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which calculation is made', unique=True)),
                ('machining_workload', models.FloatField(help_text='Cummulative assessment time for all active machining tasks')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stateduration',
            name='normal_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stateduration',
            name='overtime_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
