# Generated by Django 4.2.5 on 2023-10-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_cachedcalculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Queued'), (3, 'Back Load'), (4, 'Awaiting Material'), (5, 'In Progress'), (6, 'Completed'), (7, 'Cancelled')], default=1),
        ),
    ]
